name: build_cli

on:
  push:
    branches: [ develop ]

env:
  VERSION: 1.0.0
  BUILDDIR: "cli-1.0.0"
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: checkout code
      uses: actions/checkout@v2

    - name: get dependencies
      run: cd cmd/cli && go get -v -t -d ./...

    - name: prepare release
      run: |
        mkdir -p latest
        echo "$VERSION-$GITHUB_SHA" > latest/version.txt

    - name: build cli
      run: |
        cd cmd/cli
        GOOS=linux GOARCH=amd64 go build -o po cli.go && chmod +x po && gzip po && mv po.gz ../../latest/po-linux-$VERSION.gz
        GOOS=darwin GOARCH=amd64 go build -o po cli.go && chmod +x po && gzip po && mv po.gz ../../latest/po-mac-$VERSION.gz
        GOOS=windows GOARCH=amd64 go build -o po.exe cli.go && gzip po.exe && mv po.exe.gz ../../latest/po-win-$VERSION.zip

    - name: setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: foo
      run: |
        pwd
        ls -la
        ls -la latest

    - name: upload archives
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: latest
        destination: ${{ secrets.CLI_DOWNLOAD_BUCKET }} 
